# CloudNativePG operator values
# helm repo add cnpg https://cloudnative-pg.github.io/charts
# helm install cnpg cnpg/cloudnative-pg -n cnpg-system --create-namespace -f cloudnativepg-operator.yaml

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

monitoring:
  podMonitorEnabled: true
  grafanaDashboard:
    create: true
    namespace: monitoring
